image: docker:latest

variables:
  GOOGLE_TAG: eu.gcr.io/papers-kubernetes/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  GOOGLE_TAG_LATEST: eu.gcr.io/papers-kubernetes/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest

stages:
  - build
  - verify
  - publish

build:
  stage: build
  script:
    - docker build -t $GOOGLE_TAG .
  tags:
    - docker

verify:
  stage: verify
  before_script:
    - docker rm -f verify-$CI_COMMIT_SHA || true
  script:
    - docker run --name verify-$CI_COMMIT_SHA $GOOGLE_TAG /bin/bash -c "yarn verify"
  after_script:
    - docker rm -f verify-$CI_COMMIT_SHA || true
  tags:
    - docker

publish:
  stage: publish
  only:
    - main
  when: manual
  script:
    - docker run --env NPM_AUTH_TOKEN --name publish-$CI_COMMIT_SHA $GOOGLE_TAG ./npm-ci-publish.sh
  after_script:
    - docker rm -f publish-$CI_COMMIT_SHA || true
  tags:
    - docker

publish_beta:
  stage: publish
  when: manual
  script:
    - docker run --env NPM_AUTH_TOKEN --name publish-$CI_COMMIT_SHA $GOOGLE_TAG ./npm-ci-publish-beta-only.sh
  after_script:
    - docker rm -f publish-$CI_COMMIT_SHA || true
  tags:
    - docker
